#This configuration needs to be in the default repository branch
template: |
  ## Changes

  $CHANGES

  ## License
  Babylon Node CLI code is released under Apache 2.0 license. 
  The Babylon Node CLI applicaton is licensed under the Radix Software EULA.
  Read all terms and conditions here: http://www.radixdlt.com/terms/genericEULA
categories:
  - title: 'node-runner-cli'
    labels:
      - 'node-runner-cli'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🍏 CI & Build'
    labels:
      - 'ci'
      - 'build'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'task'
      - 'refactor'
  - title: 'Documentation'
    labels:
      - 'docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
