
= Node cli

:sectnums:
== Introduction

Executable name - radixnode

All the below commands can be executed on Ubuntu 20.04 ( supported OS) as below
[source, bash]
----
radixnode <sub command>
----

To download the cli, following instructions from [here](https://docs.radixdlt.com/main/node-and-gateway/cli-install.html)

The command line interface (CLI) provides a collection of tools for below tasks.
It is organized in a hierarchy of subcommands, and each level comes with its own built-in documentation of command syntax and options.

. To interact with node using common API calls
. To setup node quickly on a fresh ubuntu machine using docker compose or systemd
. To setup gateway on a fresh ubuntu machine using docker-compose
. To setup monitoring for the node or gateway.

For complete command reference refer document xref:docs/command_reference.adoc[Command reference]

== Interaction with node on api endpoints


To list the endpoints supported by cli
[source, bash]
----
$ radixnode api


usage: radixnode [-h] {version,system,core}
radixnode: error: the following arguments are required: apicommand
----

To list the methods supported by the endpoints say for example core endpoint

[source, bash]
----
$radixnode api core
usage: radixnode [-h]
                 {network-configuration,network-status,entity,key-list,mempool,mempool-transaction,update-validator-config}
                 ...

Core Api comands

positional arguments:
  {network-configuration,network-status,entity,key-list,mempool,mempool-transaction,update-validator-config}

account commands

positional arguments:
  {register-validator,unregister-validator,get-info}
----


== More usage instructions

To list all subcommands
[source, bash]
----
# To list the subcommands
radixnode -h
usage: radixnode.py [-h]
                    {docker,systemd,api,monitoring,version,optimise-node,auth}

positional arguments:
  {docker,systemd,api,monitoring,version,optimise-node,auth}
                        Subcommand to run

optional arguments:
  -h, --help            show this help message and exit
```
----

To list options/arguments for the subcommand
[source, bash]
----
# Check the options for a subcommand such as start-docker
radixnode docker -h

usage: radixnode.py [-h] {setup,start,stop,configure} ...

Docker commands

positional arguments:
  {setup,start,stop,configure}

optional arguments:
  -h, --help            show this help message and exit

----


== Testing with babylon releases

The babylon release is still not public. Therefor testing with babylon will be difficult.
Docker images, version references and binaries can not be fetched without authorization. Because of this, we added this
documentation as a guideline on how to work with babylon.

[source, bash]
----
# This command references https://raw.githubusercontent.com/radixdlt/babylon-nodecli
# It needs access to github in order to load the ansible files. The babylon-nodecli repository is still private.
# So a private access token (PAT) is required. This can be put into the environment variable GITHUB_TOKEN and will then
# be used to fetch the ansible script.
# See here for more information on PAT: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
export GITHUB_TOKEN="token <YOUR-PAT-HERE>"
/tmp/radixnode docker dependencies


# This command heavily uses latest_version. This function extracts the latest
# version of a resource/repo from github releases. Since the repositories are
# private, fetching the latest version also requires a PAT. See above.


export GITHUB_TOKEN="token <YOUR-PAT-HERE>"
/tmp/radixnode docker config -m CORE

# There is however not a release yet for all resources. So fetching the latest
# version might not always be possible. This is the case for the gateway for
# example. This can be solved by manually overriding the version of these resources.
# Use the below mentioned environment variables for that.
export RADIXDLT_APP_VERSION_OVERRIDE=1.3.1
export RADIXDLT_NGINX_VERSION_OVERRIDE=1.3.3
export RADIXDLT_CLI_VERSION_OVERRIDE=1.3.2
export RADIXDLT_GATEWAY_VERSION_OVERRIDE=1.5.0
/tmp/radixnode docker config -m CORE GATEWAY


----