name: Lint GitHub Actions workflows
on:
  push:
    paths:
      - '.github/**/*.yml'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "node-runner-cli"

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Check workflow files
        uses: RDXWorks-actions/action-actionlint@main
        with:
          tool_name: actionlint
          level: warning
          reporter: github-check
          filter_mode: added
          fail_on_error: true
