name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"