name: snyk

on:
  push:
    branches:
       - main
  pull_request:
    branches:
      - main
jobs:

  snyk-scan:
    runs-on: ubuntu-latest
    container:
      image: radixdlt/snyk-python:sha-e6b1b80
    permissions:
      id-token: write
      pull-requests: read
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Configure AWS credentials to fetch secrets
        uses: aws-actions/configure-aws-credentials@97271860067ec931c45b8d104fbf0d15954ab85c # branch v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_NAME_SNYK_SECRET }}
          aws-region: "eu-west-2"
          role-session-name: "baylon-nodecli-${{ github.run_id }}-${{ github.run_attempt }}"
      - name: Fetch AWS secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@287592d14d9c9c48199db83dc182ae12af3df18e # v1.0.1
        with:
          secret-ids: |
            SNYK, ${{ secrets.AWS_SECRET_NAME_SNYK }}
          parse-json-secrets: true
      - name: Run Snyk to check for deps vulnerabilities
        run: |
          cd node-runner-cli/
          pipenv install --python /usr/local/bin/python
          snyk auth ${{ env.SNYK_TOKEN }}
          snyk test --file=Pipfile --org=${{ env.SNYK_NETWORK_ORG_ID }} --severity-threshold=critical
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Snyk to check for code vulnerabilities
        run: snyk code test --file=./node-runner-cli/Pipfile --org=${{ env.SNYK_NETWORK_ORG_ID }} --severity-threshold=high
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test SBOM generation
        run: snyk sbom --file=./node-runner-cli/Pipfile --org=${{ env.SNYK_NETWORK_ORG_ID }}

  upload-sbom:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    permissions: write-all
    needs:
      - snyk-scan
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ secrets.AWS_ROLE_NAME_SNYK_SECRET }}
          app_name: 'babylon-nodecli'
          step_name: 'upload-sbom'
          secret_prefix: 'SNYK'
          secret_name: ${{ secrets.AWS_SECRET_NAME_SNYK }}
          parse_json: true
      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.6
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          cd ./node-runner-cli
          pipenv install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Snyk cli
        run: |
          npm install snyk -g
          snyk -v
          snyk auth ${{ env.SNYK_TOKEN }}
      - name: Generate SBOM
        run: snyk sbom --file=./node-runner-cli/Pipfile --org=${{ env.SNYK_NETWORK_ORG_ID }} --format=cyclonedx1.4+json --json-file-output sbom.json
      - name: Upload SBOM
        uses: AButler/upload-release-assets@c94805dc72e4b20745f543da0f62eaee7722df7a # v2.0.2
        with:
          files: sbom.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  snyk-monitor:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs:
      - snyk-scan
    permissions:
      id-token: write
      pull-requests: read
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ secrets.AWS_ROLE_NAME_SNYK_SECRET }}
          app_name: 'babylon-nodecli'
          step_name: 'snyk-monitor'
          secret_prefix: 'SNYK'
          secret_name: ${{ secrets.AWS_SECRET_NAME_SNYK }}
          parse_json: true
      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.6
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          cd ./node-runner-cli
          pipenv install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Snyk cli
        run: |
          npm install snyk -g
          snyk -v
          snyk auth ${{ env.SNYK_TOKEN }}
      - name: Enable Snyk online monitoring - Devops
        run: snyk monitor --file=./node-runner-cli/Pipfile --org=${{ env.SNYK_DEVOPS_ORG_ID }} --target-reference=${{ github.ref_name }}
      - name: Enable Snyk online monitoring - Network
        run: snyk monitor --file=./node-runner-cli/Pipfile --org=${{ env.SNYK_NETWORK_ORG_ID }} --target-reference=${{ github.ref_name }}
